"use client";

import Link from "next/link";
import { ClipboardList, MapPinned, Microscope, ScanSearch } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { FieldObservation } from "@/types/domain";

export function DashboardClient() {
  const [items, setItems] = useState<FieldObservation[]>([]); const [configured, setConfigured] = useState(true);
  useEffect(() => { fetch("/api/observations").then(async (response) => { if (!response.ok) { setConfigured(false); return; } const body = await response.json() as { data: FieldObservation[] }; setItems(body.data); }).catch(() => setConfigured(false)); }, []);
  const speciesCount = new Set(items.map((item) => item.scientificName || item.speciesName)).size;
  const locations = new Set(items.map((item) => `${item.latitude.toFixed(2)}:${item.longitude.toFixed(2)}`)).size;
  const chart = useMemo(() => { const counts = new Map<string, number>(); items.forEach((item) => counts.set(item.speciesName, (counts.get(item.speciesName) ?? 0) + item.count)); return [...counts].slice(0,6).map(([name, count]) => ({ name, count })); }, [items]);
  const cards = [{ label: "Species identified", value: speciesCount, note: "Your observations", icon: Microscope }, { label: "Observation records", value: items.length, note: "Database-backed", icon: ClipboardList }, { label: "Individuals recorded", value: items.reduce((sum, item) => sum + item.count, 0), note: "Reported field counts", icon: ScanSearch }, { label: "Survey locations", value: locations, note: "Coordinate buckets", icon: MapPinned }];
  return <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, note, icon: Icon }) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><Icon size={18} className="text-emerald-700" /></div><p className="mt-4 text-3xl font-semibold">{configured ? value.toLocaleString() : "—"}</p><p className="mt-1 text-xs text-slate-400">{configured ? note : "Sign in / configure Supabase"}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Recorded species distribution</h2><p className="mt-1 text-sm text-slate-500">Counts from the authenticated researcher’s field records</p><div className="mt-6 h-72">{chart.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" fill="#166534" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-slate-400">No observation data available.</div>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Recent field observations</h2><div className="mt-4 space-y-3">{items.slice(0,5).map((item) => <div key={item.id} className="border-b border-slate-100 pb-3"><p className="text-sm font-medium">{item.speciesName}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.observedAt).toLocaleDateString()} · {item.latitude.toFixed(3)}, {item.longitude.toFixed(3)}</p></div>)}{!items.length && <p className="text-sm leading-6 text-slate-500">No personal observation records yet. Dashboard values remain empty rather than using fabricated demo statistics.</p>}</div><Link href="/observations/new" className="mt-5 inline-block text-sm font-semibold text-emerald-800">Add an observation →</Link></section></div></>;
}
